In [1]:
#num=numeric py=python
#multidimention array support kore
#linear algebra fouriar trnasform 
# large data into array
#fast process ,built in c language,less memory,convenient

In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.2'

In [4]:
arra_1d=np.array([1,2,3,4])
print(arra_1d)

[1 2 3 4]


In [5]:
type(arra_1d)

numpy.ndarray

arra_1d.ndim

In [6]:
array_2d=np.array([[1,2,3],[1,2,3]])
print(array_2d)

[[1 2 3]
 [1 2 3]]


In [7]:
array_2d.ndim

2

# .size

In [8]:
array_2d.size#how many elements

6

# .shape

In [9]:
array_2d.shape#row ,column

(2, 3)

# .dtype     Data Type 

In [10]:
array_2d.dtype

dtype('int32')

# ones       function for decalering array

In [11]:
#ones function
#by default float data niyhe thake
array_long_declare=np.ones(5)
print(array_long_declare)

[1. 1. 1. 1. 1.]


In [12]:
array_long_declare.dtype

dtype('float64')

# 3 X 4 matrix

In [13]:
#3x4 matrix delacre by ones
array_long_multiple_decalre=np.ones((3,4))
print(array_long_multiple_decalre)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#3x4 matrix delacre by ones
array_long_multiple_decalre_int=np.ones((3,4),dtype=int )
print(array_long_multiple_decalre_int)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# matrix by zero function

In [15]:
#matrix by 0
auto_dec_zero=np.zeros((4,6))
print(auto_dec_zero)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
auto_dec_zero_bool=np.zeros((4,6),dtype=bool)
print(auto_dec_zero_bool)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [17]:
auto_dec_zero_str=np.zeros((4,6),dtype=str)
print(auto_dec_zero_str)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


# Matrrix by empty Function

In [18]:
#empty matrix
empty_matrix=np.empty((3,7))
print(empty_matrix)

[[9.16866477e-312 6.27463370e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307 5.30276956e+180 1.02941932e-071]
 [6.97531472e-076 3.25588940e-086 3.36009414e-143 6.01433264e+175
  6.93885958e+218 5.56218858e+180 3.94356143e+180]
 [8.38309455e+165 1.72047859e+184 4.08099915e+179 1.68887728e+160
  8.08013756e-144 1.50008929e+248 2.59305228e-306]]


# arange(start,end,steps)

In [19]:
arange_1d=np.arange(1,13)
print(arange_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
arange=np.arange(1,13,2)
print(arange)

[ 1  3  5  7  9 11]


# linspace()

In [21]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [22]:
array_1dto2d=arange_1d.reshape(2,6)
print(array_1dto2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [23]:
array_1dto3d=arange_1d.reshape(2,3,2)
print(array_1dto3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [24]:
#ravel multidimentional array k 1d array te convert kore
array_1dto3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [25]:
array_1dto3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [26]:
#row k column column k row korbe
array_1dto2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# transpose using .T

In [27]:
array_1dto2d.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# Mathematical operation

In [28]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [33]:
arr1-arr2


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
arr1/arr2


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
#element wise multiplication
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

# Real multiplication of matrix

In [39]:
#real matrix multiply
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [40]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# max value

In [41]:
arr1.max()

9

In [42]:
#index of max value
arr1.argmax()

8

In [43]:
# row te max valu or column a max value
arr1.max(axis=0)#0 mean coolumn  1 mean row

array([7, 8, 9])

In [44]:
arr1.max(axis=1)

array([3, 6, 9])

# Minimum value

In [45]:
arr1.min()

1

In [46]:
#index of min value
arr1.argmin()

0

In [47]:
# row te max valu or column a max value
#0 mean coolumn , 1 mean row
arr1.min(axis=1)

array([1, 4, 7])

# Row column wise sum

In [48]:
np.sum(arr1)

45

In [49]:
#column er sub
np.sum(arr1, axis=0)

array([12, 15, 18])

In [50]:
#row er sub
np.sum(arr1, axis=1)

array([ 6, 15, 24])

# Average or mean

In [51]:
#column er sub
np.mean(arr1, axis=0)

array([4., 5., 6.])

In [52]:
#row er sub
np.mean(arr1, axis=1)

array([2., 5., 8.])

In [53]:
np.mean(arr1)

5.0

# square root

In [54]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# standard deviation

In [55]:
np.std(arr1)

2.581988897471611

# exponant e to power x

In [56]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# log/log base 10 every element 

In [57]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [58]:
#log base 10
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Array slicing

In [59]:
arraymatrix=np.arange(1,101).reshape(10,10)
arraymatrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [60]:
arraymatrix[0,0]

1

In [61]:
arraymatrix.ndim

2

In [62]:
arraymatrix[0,0].ndim

0

In [63]:
#single row
arraymatrix[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
#single column
arraymatrix[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
#single column  find in 2d array
arraymatrix[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [66]:
arraymatrix[:,0:1].ndim

2

# array_2d[shurur row position , sesh row position+1 : shurur column position ,sesh column position +1]

In [67]:
#2d array er majher kono 2d array access
arraymatrix[1:4, 1:5]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35]])

In [68]:
#pura row and ekta column 2nd and 3rd
arraymatrix[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [69]:
# slicing use kore pura matrix print
arraymatrix[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [70]:
arraymatrix[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [71]:
arraymatrix[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
#size
arraymatrix.itemsize

4

In [73]:
arraymatrix.dtype

dtype('int32')

In [74]:
32/8

4.0

# Concatination and Split

In [75]:
arr4=np.arange(1,17).reshape(4,4)

In [76]:
arr5=np.arange(17,33).reshape(4,4)
print(arr5)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [77]:
list1=[2,4,6,7]
list2=[1,1,1,1]
list1+list2

[2, 4, 6, 7, 1, 1, 1, 1]

In [78]:
#column wise concatenate
np.concatenate((arr4,arr5))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [81]:
#row wise concatenate
np.concatenate((arr4,arr5),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [82]:
#column wise concatenate vertical stack
np.vstack((arr4,arr5))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [83]:
#row wise concatenate   horizontal stack
np.hstack((arr4,arr5))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [84]:
np.hstack((arr4,arr5,arr4))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [89]:
#split   arr4 k 2 vage vag kora hlo
np.split(arr4,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [92]:
listx=np.split(arr4,2)
listx

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [93]:
listx[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
type(listx)

list

In [94]:
type(listx[0])

numpy.ndarray